#!/bin/bash
wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
tar -xzvf chruby-0.3.9.tar.gz
cd chruby-0.3.9/
sudo make install
rm -f chruby-0.3.9.tar.gz
rm -rf chruby-0.3.9/
